// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mxcmmzvdqqvpmfpkldxe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Y21tenZkcXF2cG1mcGtsZHhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5OTA0NDMsImV4cCI6MjA3NDU2NjQ0M30.wD0AfB7gzr2HTSncD67oOh_IOcHWSdJSRBVEjeFHuRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});